### 책 생성
POST localhost:8061/books
Content-Type: application/json

{
  "bookIsbn": "bookIsbn1234",
  "bookName": "bookName",
  "bookDescription": "email@gmail.com",
  "bookAuthor" : "test1234",
  "bookPublisher" : "publisher",
  "bookPublishDate" : "2024-06-15",
  "bookPrice": 25.99,
  "bookSellingPrice": 19.99,
  "bookImage": "book-image-url.jpg",
  "quantity": 100
}

### 책 불러오기
GET localhost:8061/books/5
Content-Type: application/json

### 책 전체 불러오기
GET localhost:8061/books
Content-Type: application/json

### 책 수정하기
PUT localhost:8061/books
Content-Type: application/json

{
  "bookId": 5,
  "bookIsbn": "bookIsbnIsbn",
  "bookName": "bookName2",
  "bookDescription": "gmailgmail@gmail.com",
  "bookAuthor": "testAuthor",
  "bookPublisher": "publisher",
  "bookPublishDate": "2024-06-15T00:00:00.000+00:00",
  "bookPrice": 25.99,
  "bookSellingPrice": 19.99,
  "bookImage": "imageimage.jpg",
  "quantity": 110,
  "hitsCount" : 0
}

### 책 삭제하기
DELETE localhost:8061/books/1
Content-Type: application/json

###
GET localhost:8061/books/category/1/page?sortString=high-price
Content-Type: application/json

###
GET localhost:8061/books/5/addHitsCount
Content-Type: application/json

###
GET localhost:8061/books/search?query=조선
Content-Type: application/json