
### 회원 가입 (생년월일 없음)
POST localhost:8061/users/sign-up
Content-Type: application/json

{
  "userName" : "test",

  "userEmail": "test@gmail.com",
  "userPhone": "010-1234-5678",
  "userPassword": "test1234",
  "userConfirmPassword": "test1234"
}

### 회원 가입 (생년월일 있음)
POST localhost:8061/users/sign-up
Content-Type: application/json

{
  "userName" : "test",
  "userBirth": "2000-12-31",
  "userEmail": "test@gmail.com",
  "userPhone": "010-1234-5678",
  "userPassword": "test1234",
  "userConfirmPassword": "test1234"
}